[package]
name = "tide-testing"
version = "0.1.0"
authors = ["Jacob Rothstein <hi@jbr.me>"]
edition = "2018"

[features]
html = ["scraper"]

[dependencies]
scraper = { version = "0.12.0", optional = true }
serde = "1.0.114"
serde_json = "1.0.56"
tide = "0.13.0"
surf = "1.0.3"


[dev-dependencies]
async-std = { version = "1.6.2", features = ["attributes"]}
